const currencies = {
    AED: "United Arab Emirates Dirham (AED)",
    AFN: "Afghan Afghani (AFN)",
    ALL: "Albanian Lek (ALL)",
    AMD: "Armenian Dram (AMD)",
    ANG: "Netherlands Antillean Guilder (ANG)",
    AOA: "Angolan Kwanza (AOA)",
    ARS: "Argentine Peso (ARS)",
    AUD: "Australian Dollar (AUD)",
    AWG: "Aruban Florin (AWG)",
    AZN: "Azerbaijan Manat (AZN)",
    BAM: "Bosnian Convertible Mark (BAM)",
    BBD: "Barbadian or Bajan Dollar (BBD)",
    BDT: "Bangladeshi Taka (BDT)",
    BGN: "Bulgarian Lev (BGN)",
    BHD: "Bahraini Dinar (BHD)",
    BIF: "Burundian Franc (BIF)",
    BMD: "Bermudian Dollar (BMD)",
    BND: "Bruneian Dollar (BND)",
    BOB: "Bolivian Bolíviano (BOB)",
    BRL: "Brazilian Real (BRL)",
    BSD: "Bahamian Dollar (BSD)",
    BTN: "Bhutanese Ngultrum (BTN)",
    BWP: "Botswana Pula (BWP)",
    BYN: "Belarusian Ruble (BYN)",
    BYR: "Belarusian Ruble (BYR)",
    BZD: "Belizean Dollar (BZD)",
    CAD: "Canadian Dollar (CAD)",
    CDF: "Congolese Franc (CDF)",
    CHF: "Swiss Franc (CHF)",
    CLP: "Chilean Peso (CLP)",
    CNY: "Chinese Yuan Renminbi (CNY)",
    COP: "Colombian Peso (COP)",
    CRC: "Costa Rican Colon (CRC)",
    CUP: "Cuban Peso (CUP)",
    CVE: "Cape Verdean Escudo (CVE)",
    CYP: "Cypriot Pound (CYP)",
    CZK: "Czech Koruna (CZK)",
    DJF: "Djiboutian Franc (DJF)",
    DKK: "Danish Krone (DKK)",
    DOP: "Dominican Peso (DOP)",
    DZD: "Algerian Dinar (DZD)",
    EEK: "Estonian Kroon (EEK)",
    EGP: "Egyptian Pound (EGP)",
    ETB: "Ethiopian Birr (ETB)",
    EUR: "Euro (EUR)",
    FJD: "Fijian Dollar (FJD)",
    GBP: "British Pound (GBP)",
    GEL: "Georgian Lari (GEL)",
    GHS: "Ghanaian Cedi (GHS)",
    GMD: "Gambian Dalasi (GMD)",
    GNF: "Guinean Franc (GNF)",
    GRD: "Greek Drachma (GRD)",
    GTQ: "Guatemalan Quetzal (GTQ)",
    GYD: "Guyanese Dollar (GYD)",
    HKD: "Hong Kong Dollar (HKD)",
    HNL: "Honduran Lempira (HNL)",
    HRK: "Croatian Kuna (HRK)",
    HTG: "Haitian Gourde (HTG)",
    HUF: "Hungarian Forint (HUF)",
    IDR: "Indonesian Rupiah (IDR)",
    ILS: "Israeli Shekel (ILS)",
    INR: "Indian Rupee (INR)",
    IQD: "Iraqi Dinar (IQD)",
    IRR: "Iranian Rial (IRR)",
    ISK: "Icelandic Krona (ISK)",
    JMD: "Jamaican Dollar (JMD)",
    JOD: "Jordanian Dinar (JOD)",
    JPY: "Japanese Yen (JPY)",
    KES: "Kenyan Shilling (KES)",
    KGS: "Kyrgyzstani Som (KGS)",
    KHR: "Cambodian Riel (KHR)",
    KMF: "Comorian Franc (KMF)",
    KRW: "South Korean Won (KRW)",
    KWD: "Kuwaiti Dinar (KWD)",
    KYD: "Caymanian Dollar (KYD)",
    KZT: "Kazakhstani Tenge (KZT)",
    LAK: "Lao Kip (LAK)",
    LBP: "Lebanese Pound (LBP)",
    LKR: "Sri Lankan Rupee (LKR)",
    LRD: "Liberian Dollar (LRD)",
    LSL: "Basotho Loti (LSL)",
    LTL: "Lithuanian Litas (LTL)",
    LVL: "Latvian Lats (LVL)",
    LYD: "Libyan Dinar (LYD)",
    MAD: "Moroccan Dirham (MAD)",
    MDL: "Moldovan Leu (MDL)",
    MGA: "Malagasy Ariary (MGA)",
    MKD: "Macedonian Denar (MKD)",
    MMK: "Burmese Kyat (MMK)",
    MNT: "Mongolian Tughrik (MNT)",
    MOP: "Macau Pataca (MOP)",
    MRO: "Mauritanian Ouguiya (MRO)",
    MTL: "Maltese Lira (MTL)",
    MUR: "Mauritian Rupee (MUR)",
    MVR: "Maldivian Rufiyaa (MVR)",
    MWK: "Malawian Kwacha (MWK)",
    MXN: "Mexican Peso (MXN)",
    MYR: "Malaysian Ringgit (MYR)",
    MZN: "Mozambican Metical (MZN)",
    NAD: "Namibian Dollar (NAD)",
    NGN: "Nigerian Naira (NGN)",
    NIO: "Nicaraguan Cordoba (NIO)",
    NOK: "Norwegian Krone (NOK)",
    NPR: "Nepalese Rupee (NPR)",
    NZD: "New Zealand Dollar (NZD)",
    OMR: "Omani Rial (OMR)",
    PAB: "Panamanian Balboa (PAB)",
    PEN: "Peruvian Sol (PEN)",
    PGK: "Papua New Guinean Kina (PGK)",
    PHP: "Philippine Peso (PHP)",
    PKR: "Pakistani Rupee (PKR)",
    PLN: "Polish Zloty (PLN)",
    PYG: "Paraguayan Guarani (PYG)",
    QAR: "Qatari Riyal (QAR)",
    ROL: "Romanian Leu (ROL)",
    RON: "Romanian Leu (RON)",
    RSD: "Serbian Dinar (RSD)",
    RUB: "Russian Ruble (RUB)",
    RWF: "Rwandan Franc (RWF)",
    SAR: "Saudi Arabian Riyal (SAR)",
    SBD: "Solomon Islander Dollar (SBD)",
    SCR: "Seychellois Rupee (SCR)",
    SDG: "Sudanese Pound (SDG)",
    SEK: "Swedish Krona (SEK)",
    SGD: "Singapore Dollar (SGD)",
    SIT: "Slovenian Tolar (SIT)",
    SKK: "Slovak Koruna (SKK)",
    SLL: "Sierra Leonean Leone (SLL)",
    SOS: "Somali Shilling (SOS)",
    SRD: "Surinamese Dollar (SRD)",
    STD: "Sao Tomean Dobra (STD)",
    SVC: "Salvadoran Colon (SVC)",
    SYP: "Syrian Pound (SYP)",
    SZL: "Swazi Lilangeni (SZL)",
    THB: "Thai Baht (THB)",
    TJS: "Tajikistani Somoni (TJS)",
    TMM: "Turkmenistani Manat (TMM)",
    TND: "Tunisian Dinar (TND)",
    TOP: "Tongan Pa'anga (TOP)",
    TRY: "Turkish Lira (TRY)",
    TTD: "Trinidadian Dollar (TTD)",
    TWD: "Taiwan New Dollar (TWD)",
    TZS: "Tanzanian Shilling (TZS)",
    UAH: "Ukrainian Hryvnia (UAH)",
    UGX: "Ugandan Shilling (UGX)",
    UYU: "Uruguayan Peso (UYU)",
    UZS: "Uzbekistani Som (UZS)",
    VEB: "Venezuelan Bolívar (VEB)",
    VEF: "Venezuelan Bolívar (VEF)",
    VES: "Venezuelan Bolívar (VES)",
    VND: "Vietnamese Dong (VND)",
    VUV: "Ni-Vanuatu Vatu (VUV)",
    WST: "Samoan Tala (WST)",
    XAF: "Central African CFA Franc BEAC (XAF)",
    XCD: "East Caribbean Dollar (XCD)",
    XOF: "West African CFA Franc BCEAO (XOF)",
    XPF: "CFP Franc (XPF)",
    YER: "Yemeni Rial (YER)",
    ZAR: "South African Rand (ZAR)",
    ZMK: "Zambian Kwacha (ZMK)",
    ZMW: "Zambian Kwacha (ZMW)",
    ZWL: "Zimbabwean Dollar (ZWL)"
}